# Define list of variables to be used in main.tf

############
# provider #
############
variable "account_id" {
  description = "Allowed AWS account ID, to prevent you from mistakenly using an incorrect one (and potentially end up destroying a live environment)."
}

variable "region" {
  description = "This is the AWS region."
}

variable "env" {
  description = "The name of environment."
}

variable "security_group_vpc_name" {
  description = "The VPC NAME."
}

#############
# top level #
#############
variable "elb_name" {
  description = "The name of the ELB. By default generated by Terraform."
}

variable "elb_name_prefix" {
  description = "Creates a unique name beginning with the specified prefix. Conflicts with name."
}

variable "elb_internal" {
  description = "If true, ELB will be an internal ELB."
}

variable "elb_cross_zone_load_balancing" {
  description = "Enable cross-zone load balancing."
}

variable "elb_idle_timeout" {
  description = "The time in seconds that the connection is allowed to be idle."
}

variable "elb_connection_draining" {
  description = "Boolean to enable connection draining."
}

variable "elb_connection_draining_timeout" {
  description = "The time in seconds to allow for connections to drain."
}

############
# listener #
############
variable "elb_instance_port" {
  description = "The port on the instance to route to"
}

variable "elb_instance_protocol" {
  description = "The protocol to use to the instance. Valid values are HTTP, HTTPS, TCP, or SSL"
}

variable "elb_lb_port" {
  description = "The port to listen on for the load balancer."
}

variable "elb_lb_protocol" {
  description = "The protocol to listen on. Valid values are HTTP, HTTPS, TCP, or SSL."
}

################
# health_check #
################ 
variable "elb_healthy_threshold" {
  description = "The number of checks before the instance is declared healthy."
}

variable "elb_unhealthy_threshold" {
  description = "The number of checks before the instance is declared unhealthy."
}

variable "elb_timeout" {
  description = "The length of time before the check times out."
}

variable "elb_target" {
  description = "The target of the check."
}

variable "elb_interval" {
  description = "The publishing interval in minutes."
}

########
# tags #
########
variable "custom_tags" {
  type        = "map"
  description = "Custom tags"
  default     = {}
}

variable "default_tags" {
  type        = "map"
  description = "Default tags"
  default     = {}
}