# Define list of variables to be used in main.tf

############
# provider #
############
variable "account_id" {
  description = "Allowed AWS account ID, to prevent you from mistakenly using an incorrect one (and potentially end up destroying a live environment)."
}

variable "region" {
  description = "This is the AWS region."
}

#############
# top level #
#############
variable "autoscaling_group_name" {
  description = "The name of the auto scaling group. By default generated by Terraform."
}

variable "autoscaling_group_max_size" {
  description = "The maximum size of the auto scale group."
}

variable "autoscaling_group_min_size" {
  description = "The minimum size of the auto scale group."
}

variable "autoscaling_group_health_check_grace_period" {
  description = "Time (in seconds) after instance comes into service before checking health."
}

variable "autoscaling_group_health_check_type" {
  description = "Controls how health checking is done."
}

variable "autoscaling_group_desired_capacity" {
  description = "The number of Amazon EC2 instances that should be running in the group."
}

variable "autoscaling_group_force_delete" {
  description = "Allows deleting the autoscaling group without waiting for all instances in the pool to terminate."
}

variable "autoscaling_group_placement_group" {
  description = "The name of the placement group into which you'll launch your instances, if any."
}

variable "autoscaling_group_launch_configuration" {
  description = "The name of the launch configuration to use."
}

variable "autoscaling_group_vpc_zone_identifier" {
  type        = "list"
  description = "A list of subnet IDs to launch resources in."
}

variable "autoscaling_group_timeouts_delete" {
  description = "Used for destroying ASG."
}

########
# tags #
########
variable "custom_tags" {
  type        = "list"
  description = "Custom tags"
  default     = []
}

variable "default_tags" {
  type        = "list"
  description = "Default tags"
  default     = []
}
